### ISSUE TITLE
Extend database with rating system data

### ISSUE THREAD

**Issue by Japoivvb** [iLevyyy/alejandro_romero_uf3_p1#2]
1.alter table films to add a field to save rating system data using current values G, PG, PG-13, R, NC-17

2.create a feature branch to fix it

3.set label as development to be tracked

4.commit message with #numberIssue verb(in 3rd person) + details

5.create pull request and merge to main branch mention me with @name when it is ready in order to close issue please

**Comment by iLevyyy** [comment]
@Japoivvb ready to close issue
